### PR TITLE
Web tests

### PR DESCRIPTION
**Pull request by jameskleeh**

### CODE REVIEW

**Comment by jameskleeh** [comment]
We still have progress to make on this before we can start on the generator, but we're very close

**Comment by sendilkumarn** [comment]
Awesome. I kickstarted the generator migration slightly but yes we can discuss this once we are done with this changes.

**Comment by niravassar** [comment]
These are the tests that were made to pass in the web folder. The branch also has a dependency on micronaut-views 1.3.0 Snapshot which contains a new view resolver for thymeleaf

**Comment by sendilkumarn** [comment]
Thanks @niravassar for the PR :)

**Pull request merged**
